package com.tad.rest_layer.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-01-14T21:19:35.953+03:00
 * Generated source version: 3.5.5
 *
 */
@WebService(targetNamespace = "http://services.node2.tad.com/", name = "HrService")
@XmlSeeAlso({ObjectFactory.class})
public interface HrService {

    @WebMethod
    @Action(input = "http://services.node2.tad.com/HrService/fireEmployeeRequest", output = "http://services.node2.tad.com/HrService/fireEmployeeResponse")
    @RequestWrapper(localName = "fireEmployee", targetNamespace = "http://services.node2.tad.com/", className = "com.tad.node2.services.FireEmployee")
    @ResponseWrapper(localName = "fireEmployeeResponse", targetNamespace = "http://services.node2.tad.com/", className = "com.tad.node2.services.FireEmployeeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int fireEmployee(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @Action(input = "http://services.node2.tad.com/HrService/changeOrganizationRequest", output = "http://services.node2.tad.com/HrService/changeOrganizationResponse")
    @RequestWrapper(localName = "changeOrganization", targetNamespace = "http://services.node2.tad.com/", className = "com.tad.node2.services.ChangeOrganization")
    @ResponseWrapper(localName = "changeOrganizationResponse", targetNamespace = "http://services.node2.tad.com/", className = "com.tad.node2.services.ChangeOrganizationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int changeOrganization(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Long arg2
    );
}
