package com.tad.rest_layer.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2025-01-14T21:19:36.017+03:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "HrServiceService",
                  wsdlLocation = "http://localhost:8888/hr?wsdl",
                  targetNamespace = "http://services.node2.tad.com/")
public class HrServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.node2.tad.com/", "HrServiceService");
    public final static QName HrServicePort = new QName("http://services.node2.tad.com/", "HrServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/hr?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HrServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8888/hr?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HrServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HrServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HrServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HrServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HrServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HrServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HrService
     */
    @WebEndpoint(name = "HrServicePort")
    public HrService getHrServicePort() {
        return super.getPort(HrServicePort, HrService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HrService
     */
    @WebEndpoint(name = "HrServicePort")
    public HrService getHrServicePort(WebServiceFeature... features) {
        return super.getPort(HrServicePort, HrService.class, features);
    }

}
